// Generated by CoffeeScript 1.4.0
(function() {
  var blank, email, integer, presence, unique;

  integer = function(name, value, done) {
    if (!(typeof value === 'number' || toString.call(value) === '[object Number]')) {
      this.errors.add(value, 'is not a number');
    }
    return done();
  };

  unique = function(name, value, done) {
    var _this = this;
    return this.constructor.where({
      name: value
    }).first(function(err, result) {
      if (result) {
        _this.errors.add(name, 'is already taken');
      }
      return done();
    });
  };

  presence = function(name, value, done) {
    if (!value) {
      this.errors.add(name, 'is not present');
    }
    return done();
  };

  blank = function(name, value, done) {
    if (!value || value.length === 0) {
      this.errors.add(name, 'is blank');
    }
    return done();
  };

  email = function(name, value, done) {
    var email_regexp;
    email_regexp = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
    if (!email_regexp.test(value)) {
      this.errors.add(name, 'is not an email');
    }
    return done();
  };

  module.exports = {
    integer: integer,
    unique: unique,
    numeric: integer,
    presence: presence,
    email: email,
    blank: blank
  };

}).call(this);
